### ISSUE TITLE
Editing a unit causes error

### ISSUE THREAD

**Issue by brandonjank** [uidaho/smartsettia#92] opened 2017-10-23 20:18 UTC
See image
![image](https://user-images.githubusercontent.com/784730/31911179-a794cca2-b7f4-11e7-91fb-0699aa6b42e2.png)

**Comment by brec9824** [comment] 2017-10-23 21:10
@brandonjank This issue is caused by line 189 of DeviceController ```php $this->RemoveUnusedSiteLoc();``` the function got deleted in your last pull request. This line can just be removed. I hoping to have the dashboard re-fracture completed today or tomorrow and I have this removed in my branch.

**Comment by brandonjank** [comment] 2017-10-23 22:08
@brec9824 sounds good, just put this here to remind me to fix it when i get home from work. I'll leave it be, just add this issue # to your PR if you get to it.

**Comment by brec9824** [comment] 2017-11-08 05:09
Closing, fixed in pull request #96

**Closed by brec9824** 2017-11-08 05:09 UTC
Labels: bug
