### ISSUE TITLE
Cover opens when unit is locked then unlocked

### ISSUE THREAD

**Issue by brandonjank** [uidaho/smartsettia#101] opened 2017-11-07 16:50 UTC
When locking then unlocking the unit with the cover closed, the cover unexpectedly opens.

![image](https://user-images.githubusercontent.com/784730/32506110-9a7e41d8-c398-11e7-9ea2-e9aadfdbad91.png)

**Comment by brec9824** [comment] 2017-11-07 17:40
@brandonjank That is intended behavior since we are not saving the last command of the device. When the device gets unlocked it will open or close depending on the schedule.  Since you unlocked the device during open schedule and the device was closed it opened. If we want it to return to its previous state we need to store the last command for the device when it gets locked.

**Comment by brandonjank** [comment] 2017-11-07 19:09
It was closed, I locked it then unlocked it a second later, it opened. That is intended?

**Comment by brec9824** [comment] 2017-11-07 19:32
Nicks schedule code isn't working yet. So it passed the 7 am open time and didn't open (since the schedule doesn't work). Then you clicked lock and then unlock and at this point the command gets set to open or close based if the time is between 7am and 6:45pm (open) or 6:45pm and 7am (close).

**Comment by Cyberzoid1** [comment] 2017-11-07 20:08
The schedule code is done. I'm in the process of verifying it. Once i can verify its working i'll post the PR.
Currently blocked by issue #102

**Comment by brandonjank** [comment] 2017-11-07 23:30
Sounds good, we can close this when the schedule code is in production.

**Comment by brec9824** [comment] 2017-11-14 04:03
Closing, schedule code was added to production.

**Closed by brec9824** 2017-11-14 04:03 UTC
Labels: Pending
